#!/usr/bin/env bash
# =============================================================================
# gen-tfvars.sh — Write a stack's terraform.tfvars by combining:
#   (a) your own values from common.env, and
#   (b) the OUTPUTS of the stacks that came before it.
#
# This is what makes the stacks independent: nothing uses remote_state or
# reaches into another stack's state file. Values are copied forward as plain
# variables, so you can also run any stack standalone by writing its tfvars
# by hand.
#
# Usage:
#   ./gen-tfvars.sh 01      # only needs common.env
#   ./gen-tfvars.sh 03      # reads outputs of 02
#   ./gen-tfvars.sh all     # regenerate every stack that can be generated
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")"

[[ -f common.env ]] || { echo "Missing common.env — copy common.env.example and edit it."; exit 1; }
# shellcheck disable=SC1091
source ./common.env

# Turn "a,b" into a HCL list: ["a", "b"]
hcl_list() {
  local IFS=','; local out=""
  for x in $1; do out+="\"$(echo "$x" | xargs)\", "; done
  echo "[${out%, }]"
}
SUBNETS_HCL=$(hcl_list "$PRIVATE_SUBNET_IDS")

# Read one output value from a stack. Empty string if the stack isn't applied.
out() {
  local stack="$1" key="$2"
  ( cd "$stack" 2>/dev/null && terraform output -raw "$key" 2>/dev/null ) || echo ""
}

require() {
  local val="$1" what="$2" stack="$3"
  if [[ -z "$val" ]]; then
    echo "ERROR: could not read '$what' from stack $stack."
    echo "       Run 'terraform apply' in $stack first."
    exit 1
  fi
}

gen_01() {
  cat > 01-rds/terraform.tfvars <<TF
# GENERATED by gen-tfvars.sh on $(date -u '+%Y-%m-%d %H:%M UTC') — edit common.env instead.
aws_region         = "$AWS_REGION"
name_prefix        = "$NAME_PREFIX"
vpc_id             = "$VPC_ID"
private_subnet_ids = $SUBNETS_HCL
TF
  echo "wrote 01-rds/terraform.tfvars"
}

gen_02() {
  cat > 02-iam/terraform.tfvars <<TF
# GENERATED by gen-tfvars.sh on $(date -u '+%Y-%m-%d %H:%M UTC') — edit common.env instead.
aws_region  = "$AWS_REGION"
name_prefix = "$NAME_PREFIX"
enable_ssm  = true
TF
  echo "wrote 02-iam/terraform.tfvars"
}

gen_03() {
  local cra nra
  cra=$(out 02-iam cluster_role_arn); require "$cra" cluster_role_arn 02-iam
  nra=$(out 02-iam node_role_arn);    require "$nra" node_role_arn    02-iam
  cat > 03-eks/terraform.tfvars <<TF
# GENERATED by gen-tfvars.sh on $(date -u '+%Y-%m-%d %H:%M UTC')
# Role ARNs copied from stack 02's outputs.
aws_region   = "$AWS_REGION"
cluster_name = "$CLUSTER_NAME"
k8s_version  = "$K8S_VERSION"

cluster_role_arn = "$cra"
node_role_arn    = "$nra"

private_subnet_ids = $SUBNETS_HCL

# [] = no uncapped built-in pool, so stack 04's node cap is the real ceiling.
builtin_node_pools     = []
endpoint_public_access = true
TF
  echo "wrote 03-eks/terraform.tfvars"
}

gen_04() {
  local nrn csg cn
  nrn=$(out 02-iam node_role_name);            require "$nrn" node_role_name            02-iam
  cn=$(out  03-eks cluster_name);              require "$cn"  cluster_name              03-eks
  csg=$(out 03-eks cluster_security_group_id); require "$csg" cluster_security_group_id 03-eks
  cat > 04-nodepool/terraform.tfvars <<TF
# GENERATED by gen-tfvars.sh on $(date -u '+%Y-%m-%d %H:%M UTC')
# node_role_name from stack 02; cluster values from stack 03.
aws_region = "$AWS_REGION"

cluster_name              = "$cn"
cluster_security_group_id = "$csg"
node_role_name            = "$nrn"

private_subnet_ids = $SUBNETS_HCL

max_nodes     = $MAX_NODES
vcpu_per_node = $VCPU_PER_NODE

allowed_architectures = ["arm64", "amd64"]
capacity_types        = ["on-demand"]
TF
  echo "wrote 04-nodepool/terraform.tfvars"
}

gen_05() {
  local cn ep port dbn dbu ssmp
  cn=$(out   03-eks cluster_name);         require "$cn"   cluster_name         03-eks
  ep=$(out   01-rds rds_endpoint);         require "$ep"   rds_endpoint         01-rds
  port=$(out 01-rds rds_port)
  dbn=$(out  01-rds db_name)
  dbu=$(out  01-rds db_username)
  ssmp=$(out 01-rds db_password_ssm_path)
  cat > 05-keycloak/terraform.tfvars <<TF
# GENERATED by gen-tfvars.sh on $(date -u '+%Y-%m-%d %H:%M UTC')
# Cluster from stack 03; database from stack 01.
# No password here on purpose — it is read from SSM at apply time.
aws_region = "$AWS_REGION"

cluster_name = "$cn"

rds_endpoint         = "$ep"
rds_port             = ${port:-5432}
db_name              = "${dbn:-keycloak}"
db_username          = "${dbu:-keycloak}"
db_password_ssm_path = "${ssmp:-/keycloak/db/password}"

namespace        = "keycloak"
keycloak_version = "$KEYCLOAK_VERSION"
replicas         = $REPLICAS
hostname_strict  = false
ingress_enabled  = false

offline_mode            = $OFFLINE_MODE
artifactory_host        = "$ARTIFACTORY_HOST"
artifactory_docker_repo = "$ARTIFACTORY_DOCKER_REPO"
artifactory_helm_repo   = "$ARTIFACTORY_HELM_REPO"
artifactory_username    = "$ARTIFACTORY_USERNAME"
TF
  echo "wrote 05-keycloak/terraform.tfvars"
  if [[ "$OFFLINE_MODE" == "true" ]]; then
    echo ""
    echo "Offline mode is on. Supply the Artifactory password out-of-band:"
    echo '  export TF_VAR_artifactory_password="$(aws ssm get-parameter \'
    echo "    --name /keycloak/artifactory/password --with-decryption \\"
    echo '    --query Parameter.Value --output text)"'
  fi
}

case "${1:-}" in
  01) gen_01 ;;
  02) gen_02 ;;
  03) gen_03 ;;
  04) gen_04 ;;
  05) gen_05 ;;
  all)
    gen_01; gen_02
    gen_03 2>/dev/null || echo "skipped 03 (stack 02 not applied yet)"
    gen_04 2>/dev/null || echo "skipped 04 (stack 02/03 not applied yet)"
    gen_05 2>/dev/null || echo "skipped 05 (stack 01/03 not applied yet)"
    ;;
  *) echo "Usage: $0 {01|02|03|04|05|all}"; exit 1 ;;
esac
